site_name: FC Fulbert
site_url: https://clpetiot.github.io/FC-Fulbert/
site_description: Football Club Fulbert à Chartres — actualités, résultats, entraînements, inscriptions. FC Fulbert Chartres, club de football en Eure-et-Loir.
use_directory_urls: true

theme:
  name: material
  language: fr
  favicon: images/favicon.ico
  custom_dir: overrides

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FCFulbert
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/FCFulbert

nav:
  - Accueil: index.md
  - Contact: contact.md
  - Événements: evenements.md

plugins:
  - search

markdown_extensions:
  - meta

extra_css:
  - css/extra.css?v=20251001