site_name: FC Fulbert
site_url: https://cleptiot.github.io/FC-Fulbert/
site_description: Site officiel du FC Fulbert - actualités, joueurs, résultats et infos du club.

theme:
  name: material
  language: fr

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FCFulbert
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/FCFulbert

nav:
  - Accueil: index.md
  - Contact: contact.md

extra_css:
  - css/extra.css

