site_name: FC Fulbert
site_url: https://cleptiot.github.io/FC-Fulbert/
site_description: Site officiel du FC Fulbert - actualités, joueurs, résultats et infos du club.

theme:
  name: material
  language: fr

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FCFulbert
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/FCFulbert

nav:
  - Accueil: index.md
  - Histoire: histoire.md
  - Effectif: effectif.md
  - Matchs: matchs.md
  - Actualités: actualites.md
  - Contact: contact.md

plugins:
  - search
  - sitemap:
      changefreq: daily
      priority: 0.5
  - seo
plugins:
  - meta-descriptions:
      min_length: 50
      max_length: 160

