site_name: FC Fulbert
site_url: https://clpetiot.github.io/FC-Fulbert/
site_description: Site officiel du FC Fulbert - actualités, joueurs, résultats et infos du club.
use_directory_urls: true

theme:
  name: material
  language: fr

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FCFulbert
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/FCFulbert

nav:
  - Accueil: index.md
  - Contact: contact.md

plugins:
  - search
  - meta-descriptions:
      min_length: 50
      max_length: 160

extra_css:
  - css/extra.css?v=2
